name: GitHub Actions 실행시켜보기

on:
  push:
      branches:
        - main
jobs:
  My-Deploy-job:
    runs-on: ubuntu-latest

    steps:
     - name: Hello Word 찍기
       run: echo "Hello World"
     - name: 여러명령어 작성하기
       run: |
        echo "Good"
        echo "Morning"